-----EDA ON COVID.
---1.query for the trend of daily new cases and daily new deaths country wise

SELECT LOCATION,DATE,NEW_DEATHS,
	NEW_CASES
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2;

---2.query for the trend of Cumulative daily cases and Cumulative daily deaths countrywise

SELECT LOCATION,DATE,TOTAL_DEATHS,
	TOTAL_CASES
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2;

---3. Daily variation in cumulative percentage of people who dead who contracted covid...countrywise

SELECT LOCATION,DATE,TOTAL_DEATHS,
	TOTAL_CASES,
	(CAST(TOTAL_DEATHS AS DECIMAL) / TOTAL_CASES) * 100 AS DEATHPERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
	AND TOTAL_CASES <> 0
ORDER BY 1,2;

---4.Overall percentage of people died who contracted covid...countrywise

SELECT LOCATION,
	MAX(TOTAL_DEATHS) AS TD,
	MAX(TOTAL_CASES) AS TC,
	(CAST(MAX(TOTAL_DEATHS) AS DECIMAL) / MAX(TOTAL_CASES)) * 100 AS DEATHPERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
HAVING MAX(TOTAL_CASES) <> 0
ORDER BY 1;

---5.Overall percentage of people who contracted covid wrt to population...countrywise

SELECT LOCATION,
	POPULATION,
	MAX(TOTAL_CASES) AS TC,
	(CAST(MAX(TOTAL_CASES) AS DECIMAL) / POPULATION) * 100 AS INFECTEDPERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
	AND POPULATION <> 0
GROUP BY LOCATION,
	POPULATION
ORDER BY 4;

---6.Overall percentage of people dead who contracted covid wrt to population...countrywise

SELECT LOCATION,
	POPULATION,
	MAX(TOTAL_DEATHS) AS TD,
	(CAST(MAX(TOTAL_DEATHS) AS DECIMAL) / POPULATION) * 100 AS DEATHPERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
	AND POPULATION <> 0
GROUP BY LOCATION,
	POPULATION
ORDER BY 4 DESC;

----CONTINENT
 ---7.total cases by continent
 --1ST QUERY USING CTE
 WITH TOTALCASE AS
	(SELECT CONTINENT,
			LOCATION,
			MAX(TOTAL_CASES) AS TC
		FROM COVID_DEATHS
		WHERE CONTINENT IS NOT NULL
		GROUP BY CONTINENT,
			LOCATION)
            
SELECT CONTINENT,
	SUM(TC)
FROM TOTALCASE
GROUP BY 1;

---2ND QUERY

SELECT CONTINENT,
	SUM(NEW_CASES)
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY 1
ORDER BY 1;

---8.total deaths by continent
 --1ST QUERY USING CTE
 WITH TOTALDEATH AS
	(SELECT CONTINENT,
			LOCATION,
			MAX(TOTAL_DEATHS) AS TD
		FROM COVID_DEATHS
		WHERE CONTINENT IS NOT NULL
		GROUP BY CONTINENT,
			LOCATION)
            
 SELECT CONTINENT,
	SUM(TD)
 FROM TOTALCASE
 GROUP BY 1;

---2ND QUERY

SELECT CONTINENT,
	SUM(NEW_DEATHS)
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY 1
ORDER BY 1;

---9. 3 most affected countries by covid in each continent by no. of deaths
WITH COVID_DEATHS AS
	(SELECT CONTINENT,
			LOCATION,
			MAX(TOTAL_DEATHS) AS TD,
			RANK() OVER (PARTITION BY CONTINENT ORDER BY MAX(TOTAL_DEATHS) DESC) AS R
		FROM COVID_DEATHS
		WHERE CONTINENT IS NOT NULL
		GROUP BY CONTINENT,
			LOCATION
		HAVING MAX(TOTAL_DEATHS) IS NOT NULL)
 SELECT *
 FROM COVID_DEATHS
 WHERE R IN (1,2,3) ;

---10. 3 least affected countries by covid in each continent by no. of deaths
WITH COVID_DEATHS AS
	(SELECT CONTINENT,
			LOCATION,
			MAX(TOTAL_DEATHS) AS TD,
			RANK() OVER (PARTITION BY CONTINENT ORDER BY MAX(TOTAL_DEATHS) ASC) AS R
		FROM COVID_DEATHS
		WHERE CONTINENT IS NOT NULL
		GROUP BY CONTINENT,
			LOCATION
		HAVING MAX(TOTAL_DEATHS) IS NOT NULL)
        
 SELECT *
 FROM COVID_DEATHS
 WHERE R IN (1,2,3) ;

---11. 3 most affected countries by covid in each continent by no. of CASEs
WITH COVID_CASES AS
	(SELECT CONTINENT,
			LOCATION,
			MAX(TOTAL_CASES) AS TC,
			RANK() OVER (PARTITION BY CONTINENT ORDER BY MAX(TOTAL_CASES) DESC) AS R
		FROM COVID_DEATHS
		WHERE CONTINENT IS NOT NULL
		GROUP BY CONTINENT,
			LOCATION
		HAVING MAX(TOTAL_CASES) IS NOT NULL)
        
 SELECT *
 FROM COVID_CASES
 WHERE R IN (1,2,3) ;

---12. 3 least affected countries by covid in each continent by no. of cases
WITH COVID_CASES AS
	(SELECT CONTINENT,
			LOCATION,
			MAX(TOTAL_CASES) AS TC,
			RANK() OVER (PARTITION BY CONTINENT ORDER BY MAX(TOTAL_CASES) ASC) AS R
		FROM COVID_DEATHS
		WHERE CONTINENT IS NOT NULL
		GROUP BY CONTINENT,
			LOCATION
		HAVING MAX(TOTAL_CASES) IS NOT NULL)
        
 SELECT *
 FROM COVID_CASES
 WHERE R IN (1,2,3) ;

---13.GLOBAL DAILY CASES

SELECT date,SUM(NEW_CASES) AS NS,
	SUM(NEW_DEATHS) AS ND
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY date
ORDER BY date 

---14.differentiating countries into mildly affected,severly affected,very severly affected
---based on the percentage of population affected by covid by creating view

DROP VIEW IF EXISTS SEVERITY;
CREATE VIEW SEVERITY AS
SELECT LOCATION,
	POPULATION,
	MAX(TOTAL_CASES) AS TD,
	(CAST(MAX(TOTAL_CASES) AS DECIMAL) / POPULATION) * 100 AS INFECTEDPERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
	AND POPULATION <> 0
GROUP BY LOCATION,
	POPULATION ;

SELECT *,
	CASE
		WHEN INFECTEDPERCENTAGE <= 1 THEN 'mildly affected'
		WHEN INFECTEDPERCENTAGE BETWEEN 1 AND 5 THEN 'severly affected'
		WHEN INFECTEDPERCENTAGE >= 5 THEN 'very severly affected'
	END AS AFFECTEDPERCEPTION
FROM SEVERITY
WHERE INFECTEDPERCENTAGE IS NOT NULL
ORDER BY INFECTEDPERCENTAGE;

--15. Percentage of Population that has recieved  Covid Vaccine

SELECT DEA.CONTINENT,
	DEA.LOCATION,
	DEA.DATE,
	DEA.POPULATION,
	VAC.NEW_VACCINATIONS,
	SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVID_DEATHS DEA
INNER JOIN COVID_VACCINATION VAC ON 
    DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3

